<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>NgStationTool</AssemblyName>
    <RootNamespace>NgStationTool</RootNamespace>
    <Version>1.5.2</Version>
    <Product>NG 工位流转中心</Product>
    <Description>图片 A/B 流转 + XML DMC 门控 + 云端 Log 按键放行（Win10）</Description>
    <LangVersion>latest</LangVersion>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
      </PropertyGroup>

</Project>
